### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by ArielS1** [postmen/node-cloud-print#6]
i try to use 
npm install git://github.com/postmen/node-cloud-print.git
or
npm install cloud-print
and i get the following error:

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit  git+ssh://git@github.com/postmen/google-api-nodejs-client.git resetting remote C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46: Cloning into bare repository 'C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46'...
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46: Host key verification failed.
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46:
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46: and the repository exists.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cloud-print"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/postmen/google-api-nodejs-client.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46
npm ERR! Cloning into bare repository 'C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-postmen-google-api-nodejs-client-git-21a89f46'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tmunot\npm-debug.log

**Comment by alizehctl** [comment]
Couldn't install it either
